apiVersion: apps/v1
kind: Deployment
metadata:
  name: locations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: locations
  template:
    metadata:
      labels:
        app: locations
        version: v1
    spec:
      containers:
      - name: locations
        image: gcr.io/circle-ci-256918/location/circle-ci:f4d9fe6849002b587f38ccaddfbcbcdf614c1215
        imagePullPolicy: "Always"
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: locations
  labels:
    app: locations
spec:
  selector:
    app: locations
  ports:
  - name: http
    port: 8081
    targetPort: 8080
