apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
        version: v1
    spec:
      containers:
      - name: reservation
        image: gcr.io/prod-258311-258406/reservation/prod-258311:a1c8a8220ade8babafaf2193fc74c31f39239567
        ports:
        - name: http
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  selector:
    app: reservation
  ports:
  - name: http
    port: 8082
    targetPort: 8080
