version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - run:
        name: install
        command: npm install
      - run:
        name: run semantic globally
        command: npx semantic-release
      - run:
        name: release
        command: npm run semantic-release || true
